name: workflow1

on:
  push:
    branches: ['main']
    
    
jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps:
     run: echo "Hello"
     
  job2:
    runs-on: ubuntu-latest
    steps:
      run: echo "world"
